creation composant category / CSS composant category (draft)
WildCodeSchool-2024-02/JS-RMT-julien-TeamB-Project2 pull request #12
Opened 2024-05-29 10:06 UTC by BertrandLrc

Création du composant category.
En tant qu'utilisateur je peux cliquer sur le bouton catégories afin de visualiser les différentes catégories.

2024-05-29 10:09 UTC, Megane45 submitted a review, later dismissed

2024-05-29 10:09 UTC, OrestiHoxhallari approved these changes

2024-05-29 10:14 UTC, DylanRobinaud approved these changes

2024-05-29 10:47 UTC, jujuck requested changes

2024-05-29 10:47 UTC, jujuck commented on client/src/components/CategoryComponent.jsx
> +      <h1>GENRES</h1>
LEs datass doivent venir du Back End, Cf Mégane pour la route genres

2024-05-30 15:25 UTC, BertrandLrc commented
En tant qu'utilisateur je peux cliquer sur le bouton catégories afin de visualiser les différentes catégories.
En tant qu'utilisateur je peux cliquer sur le lien toutes les catégories pour naviguer vars le catalogue.

2024-05-31 07:01 UTC, Megane45 approved these changes

2024-05-31 07:26 UTC, OrestiHoxhallari submitted a review, later dismissed

2024-05-31 08:13 UTC, DylanRobinaud approved these changes

2024-05-31 08:44 UTC, jujuck requested changes

2024-05-31 08:44 UTC, jujuck commented on client/src/components/Navigation.jsx
> +        <ul className="navButtonContainer">
mettre des li

2024-05-31 09:58 UTC, Megane45 approved these changes

2024-05-31 09:58 UTC, BertrandLrc commented
Ajout li dans nav et finalisation du css category

2024-05-31 10:16 UTC, OrestiHoxhallari approved these changes

2024-05-31 11:10 UTC, BertrandLrc commented
media querie

2024-05-31 12:03 UTC, DylanRobinaud approved these changes

2024-05-31 12:03 UTC, Megane45 approved these changes

2024-05-31 12:05 UTC, OrestiHoxhallari approved these changes

2024-05-31 12:11 UTC, jujuck approved these changes

2024-05-31 12:11 UTC, merged