Cart.components
WildCodeSchool-2024-02/JS-RMT-julien-TeamB-Project2 pull request #2
Opened 2024-05-23 14:37 UTC by BertrandLrc

Creation composant panier avec css

2024-05-23 14:41 UTC, DylanRobinaud submitted a review, later dismissed
Un travail vraiment impressionant !

2024-05-23 14:42 UTC, OrestiHoxhallari submitted a review, later dismissed
ITS GOOD

2024-05-24 07:44 UTC, Megane45 submitted a review, later dismissed
Good

2024-05-24 07:59 UTC, jujuck requested changes

2024-05-24 07:59 UTC, jujuck commented on client/.gitignore
> +.CartComponent.css
Ne pas mettre dans le fichier

2024-05-24 07:59 UTC, jujuck commented on client/src/components/CartComponent.css
> +.shopContainer {
Mettre en place une convention de nommage

2024-05-24 07:59 UTC, jujuck commented on server/app/router.js
Ajouter une route spécifique qui renvoie 3 ou 4 items

2024-05-24 07:59 UTC, jujuck commented on client/src/pages/Cart.jsx
> +      <section className="shopContainer">
mettre en place le map sur la data

2024-05-24 09:51 UTC, Megane45 submitted a review, later dismissed
niquel

2024-05-24 09:52 UTC, OrestiHoxhallari approved these changes

2024-05-24 09:56 UTC, DylanRobinaud approved these changes
C'est OK

2024-05-24 09:56 UTC, Megane45 submitted a review, later dismissed
niquel

2024-05-24 10:05 UTC, OrestiHoxhallari approved these changes

2024-05-24 10:34 UTC, jujuck requested changes

2024-05-24 10:34 UTC, jujuck commented on client/src/App.css
> +.cartTitle1 {
Pb de nommage

2024-05-24 10:34 UTC, jujuck commented on client/src/components/CartComponent.jsx
> +        <h2 className="cartTitle2">{title}</h2>
supprimer la class et viser le p

2024-05-24 10:34 UTC, jujuck commented on client/src/main.jsx
> +      .get("http://localhost:3310/api/basket")
utiliser .env

2024-05-24 12:58 UTC, Megane45 submitted a review, later dismissed
good

2024-05-24 13:31 UTC, DylanRobinaud submitted a review, later dismissed
OK

2024-05-24 13:52 UTC, OrestiHoxhallari submitted a review, later dismissed

2024-05-24 15:26 UTC, jujuck approved these changes

2024-05-24 15:30 UTC, merged