Modification du style sur la page Article et ajout d'une classe speci…
WildCodeSchool-2024-02/JS-RMT-julien-TeamB-Project2 pull request #25
Opened 2024-06-03 11:59 UTC by Megane45

sur la page Article et ajout d'une classe specifique a cette page

2024-06-03 13:03 UTC, DylanRobinaud commented on client/src/components/ArticleComponents.css
> +  .btn {
Nom de la class css pas assez explicite articleButton serait peut-être plus approprié

2024-06-03 13:04 UTC, DylanRobinaud commented on client/src/components/ArticleComponents.css
> +    font-family: Roboto, sans-serif;
font déja déclaré dans le fichier App.css

2024-06-03 13:04 UTC, DylanRobinaud commented on client/src/components/ArticleComponents.css
> +    font-size: 15px;
px =>rem

2024-06-03 13:04 UTC, DylanRobinaud commented on client/src/components/ArticleComponents.css
> +    padding: 10px 30px;
px =>rem

2024-06-03 13:05 UTC, DylanRobinaud commented on client/src/components/ArticleComponents.css
> +    color: #fff;
var déclaré dans le fichier App.css

2024-06-03 13:05 UTC, DylanRobinaud commented on client/src/components/ArticleComponents.css
> +    padding: 10px 18px;
px =>rem

2024-06-03 13:06 UTC, DylanRobinaud commented on client/src/components/ArticleComponents.css
> +    color: #ffffff;
var dans App.css

2024-06-03 13:06 UTC, DylanRobinaud commented on client/src/components/ArticleComponents.jsx
> +        <button className="btn" type="button" onClick={() => addToCart(game)}>
modifié la className comme écrit plus haut

2024-06-04 08:16 UTC, DylanRobinaud commented on client/src/components/ArticleComponents.css
> +    font-size: 1.2rem;
var() dispo dans app

2024-06-04 08:25 UTC, BertrandLrc submitted a review, later dismissed

2024-06-04 08:25 UTC, OrestiHoxhallari approved these changes

2024-06-04 08:30 UTC, OrestiHoxhallari submitted a review, later dismissed

2024-06-04 08:30 UTC, BertrandLrc approved these changes

2024-06-04 08:51 UTC, BertrandLrc approved these changes
lets go

2024-06-04 08:52 UTC, DylanRobinaud approved these changes

2024-06-04 09:49 UTC, jujuck requested changes
Split en plusieurs PR par U.S et fix

2024-06-04 09:49 UTC, jujuck commented on client/src/components/CartComponent.jsx
> +          Quantité :{" "}
Espace en trop

2024-06-04 09:49 UTC, jujuck commented on client/src/components/ArticleComponents.css
> +  .gameCardImg.article {
Attention, doublon de css

2024-06-05 10:00 UTC, closed without merging