Home.news.component
WildCodeSchool-2024-02/JS-RMT-julien-TeamB-Project2 pull request #29
Opened 2024-06-04 09:59 UTC by DylanRobinaud

Création d'un composent News
Rajout d'une API 
Utilisation de l'API pour afficher différents articles au hasard
Rajout du CSS

2024-06-04 13:24 UTC, BertrandLrc submitted a review, later dismissed

2024-06-04 13:27 UTC, OrestiHoxhallari approved these changes

2024-06-04 13:42 UTC, Megane45 approved these changes

2024-06-04 14:26 UTC, jujuck requested changes

2024-06-04 14:26 UTC, jujuck commented on client/src/components/NewsHome.jsx
> +                <img src={article.urlToImage} alt="PhotoDeL'Article" />
A corriger, infos différentes pour chaque carte sur alt

2024-06-04 14:26 UTC, jujuck commented on client/src/components/NewsHome.jsx
> +          "https://newsapi.org/v2/everything/?q=gaming&language=fr&apiKey=a957ae1f88df4d6885bd3de972fb6ebf"
La mettre en variable d'environnement

2024-06-05 13:56 UTC, BertrandLrc approved these changes

2024-06-05 13:58 UTC, OrestiHoxhallari approved these changes

2024-06-05 13:59 UTC, Megane45 approved these changes

2024-06-05 15:28 UTC, jujuck approved these changes

2024-06-05 20:50 UTC, OrestiHoxhallari approved these changes

2024-06-06 06:55 UTC, Megane45 approved these changes

2024-06-06 07:28 UTC, BertrandLrc approved these changes

2024-06-06 09:45 UTC, jujuck approved these changes

2024-06-06 09:46 UTC, merged