Component catalog
WildCodeSchool-2024-02/JS-RMT-julien-TeamB-Project2 pull request #3
Opened 2024-05-23 14:44 UTC by OrestiHoxhallari

2024-05-23 14:49 UTC, DylanRobinaud approved these changes
Pas mal, pas mal !

2024-05-23 14:53 UTC, BertrandLrc requested changes
CSS a revoir ensemble donc non bloquant (notamment la synthaxe  et le nommage des rubriques).
Par contre modifier Catalog.css ligne 41 en text-align: center !

2024-05-23 15:00 UTC, BertrandLrc approved these changes
ok pour moi

2024-05-23 15:02 UTC, DylanRobinaud approved these changes
Validez !

2024-05-24 07:45 UTC, Megane45 approved these changes
good

2024-05-24 07:54 UTC, jujuck requested changes

2024-05-24 07:54 UTC, jujuck commented on client/src/components/Catalog.css
> +.GameCard-UL {
Mettre en place une convention de nommage

2024-05-24 07:54 UTC, jujuck commented on client/src/components/GameCard.jsx
> +import './Catalog.css';
Nom du fichier correspond au nom du composant

2024-05-24 07:54 UTC, jujuck commented on client/src/components/VideoGames.jsx
> +        const response = await axios.get(apiUrl);
Mettre en place directement l'url

2024-05-24 07:54 UTC, jujuck commented on client/src/components/VideoGames.jsx
> +    const fetchGames = async () => {
mettre la fonction en dehors du useEffect

2024-05-24 07:54 UTC, jujuck commented on client/src/components/VideoGames.jsx
> +
Trop de ligne vide, une seule

2024-05-24 07:54 UTC, jujuck commented on client/src/main.jsx
> +    loader: () => axios.get('http://localhost:3310/api/games')
Fait un choix de chargement

2024-05-24 07:54 UTC, jujuck commented on client/src/pages/Catalog.jsx
> +    <section className="">
si className est vide ?

2024-05-24 09:51 UTC, DylanRobinaud submitted a review, later dismissed
Joli modif!

2024-05-24 09:51 UTC, Megane45 approved these changes
niquel

2024-05-24 09:52 UTC, BertrandLrc submitted a review, later dismissed
ok pour moi

2024-05-24 10:27 UTC, jujuck requested changes

2024-05-24 10:27 UTC, jujuck commented on client/src/components/GameCard.css
> +.gamecardBottom {
pb de nommage gameCardBottom ou sur gameCardImg

2024-05-24 10:27 UTC, jujuck commented on client/src/components/GameCard.jsx
> +    <li className='GameCard-LI'>
??? a supprimer

2024-05-24 10:27 UTC, jujuck commented on client/src/components/GameCard.jsx
> +      <div className="Top">
??? POurquoi

2024-05-24 10:27 UTC, jujuck commented on client/src/main.jsx
> +    loader: () => axios.get('http://localhost:3310/api/games')
Profite pour le .env

2024-05-24 10:27 UTC, jujuck commented on client/src/pages/Catalog.jsx
> +    <section>
POurquoi une section vide ?

2024-05-24 10:51 UTC, Megane45 approved these changes
Good

2024-05-24 12:55 UTC, BertrandLrc submitted a review, later dismissed
ok pour moi

2024-05-24 12:57 UTC, DylanRobinaud approved these changes
gg

2024-05-24 15:16 UTC, jujuck submitted a review, later dismissed

2024-05-24 15:24 UTC, merged