Component.nav
WildCodeSchool-2024-02/JS-RMT-julien-TeamB-Project2 pull request #4
Opened 2024-05-23 14:59 UTC by DylanRobinaud

- Création de la Navigation
- Rajout de la Navigation sur toutes les pages
- Mise en place des éléments sur la page (CSS)
- Rajout des logos Accueil et Panier

2024-05-23 15:03 UTC, BertrandLrc submitted a review, later dismissed
ok pour moi

2024-05-23 15:03 UTC, OrestiHoxhallari approved these changes

2024-05-24 07:45 UTC, Megane45 submitted a review, later dismissed
good

2024-05-24 08:35 UTC, jujuck requested changes
Pour l'ajout de la nav, pense à regarder l'ajout d'un layout à test pages sur la doc react router DOM

2024-05-24 08:35 UTC, jujuck commented on client/src/components/Navigation.css
> +.logoSize {
Idem, mise en place d'une convention

2024-05-24 08:35 UTC, jujuck commented on server/app/router.js
> +// Route to get a list of games
Ce n'est pas à toi de faire des changements sur ce fichier, il ne fait pas parti de ta fonctionnalité

2024-05-24 08:49 UTC, DylanRobinaud commented
Modification PR

2024-05-24 08:54 UTC, OrestiHoxhallari approved these changes

2024-05-24 08:54 UTC, Megane45 approved these changes
niquel

2024-05-24 09:51 UTC, BertrandLrc commented
ok

2024-05-24 09:51 UTC, BertrandLrc approved these changes

2024-05-24 10:21 UTC, merged