creation context/ajout bouton article/ajout bouton cart
WildCodeSchool-2024-02/JS-RMT-julien-TeamB-Project2 pull request #7
Opened 2024-05-28 10:25 UTC by BertrandLrc

Création du dossier context et du fichier CartContext.jsx afin de gérer les states du panier.
Modification du main.jsx pour supprimer le loader du panier et encapsuler l'ensemble des routes avec le context.
Modif du fichier ArticleComponent.jsx : en tant qu'utilisateur je peux ajouter l'article au panier.
Modif du fichier CartComponent.jsx : en tant qu'utilisateur je peux supprimer l'article du panier.
Intégration d'un ternaire dans le cart.jsx afin d'afficher l'article ou sinon Votre panier est vide.

2024-05-28 10:37 UTC, DylanRobinaud approved these changes
perfect !!

2024-05-28 12:25 UTC, Megane45 approved these changes

2024-05-28 13:11 UTC, OrestiHoxhallari approved these changes

2024-05-28 13:43 UTC, jujuck requested changes

2024-05-28 13:43 UTC, jujuck commented on client/src/components/CartComponent.jsx
> +        <button type="button" onClick={handleRemove}>Retirer du panier</button>
utiliser directement removeFromCart(id) dans le onClick.

2024-05-28 13:43 UTC, jujuck commented on client/src/main.jsx
> +    path: "/article/:id",
Désolé, mais la route, c'est articles/:id. De plus, cela n'a absolument rien à voir avec la mise en place du contexte!!!

2024-05-28 14:36 UTC, Megane45 approved these changes

2024-05-29 06:54 UTC, jujuck approved these changes

2024-05-29 06:54 UTC, merged